### ISSUE TITLE
Remove unassigned keys from locales

### ISSUE THREAD

**Issue by brawaru** [Sasha-Sorokin/alphaid-bot#4]
If key was not assigned to anyone, then remove it after the modules' initialization.

This may reduce memory used by the bot instance, but slightly affect boot time.

## Roadmap 

- [x] Make Module Loader fire events for stages
- [x] Make it possible to get all the language keys
- [x] Make cleaner module on top of APIs above
